name: Notify Teams on Push

on:
  push:
    branches:
      - main  # or any branch you want to monitor

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send notification to Teams
        run: |
          curl -H 'Content-Type: application/json' \
               -d '{
                     "text": "New push to repository: ${{ github.repository }} by ${{ github.actor }}. Commit message: ${{ github.event.head_commit.message }}"
                   }' \
               ${{ secrets.TEAMS_WEBHOOK_URL }}
