# Workflow derived from https://github.com/r-lib/actions/tree/v2/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
on:
  push:
    branches: [main, master]
  pull_request:

name: test-coverage.yaml

permissions: read-all

jobs:
  test-coverage:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      GROQ_API_KEY: ${{ secrets.GROQ_API_KEY }}

    steps:
      - uses: actions/checkout@v4

      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true
          r-version: '4.5.1'

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::covr, any::xml2, any::plumber, any::logger
          needs: coverage
          cache-version: 1

      - name: Start Papercheck API
        run: |
          cd inst/plumber
          nohup Rscript run_api.R > api.log 2>&1 &
          echo $! > api.pid
          # Wait for API to be ready
          for i in {1..30}; do
            if curl -s http://localhost:2005/health > /dev/null 2>&1; then
              echo "API is ready"
              break
            fi
            echo "Waiting for API to start... ($i/30)"
            sleep 2
          done
          cat api.log
        shell: bash

        # this step should be revisited to still publish a report when a test fails
        # , which is not the case now
      - name: Test coverage
        run: |
          cov <- covr::package_coverage(
            quiet = FALSE,
            clean = FALSE,
            install_path = file.path(normalizePath(Sys.getenv("RUNNER_TEMP"), winslash = "/"), "package")
          )
          print(cov)
          covr::to_cobertura(cov)
        shell: Rscript {0}

      - uses: codecov/codecov-action@v5
        with:
          fail_ci_if_error: true
          files: ./cobertura.xml
          token: ${{ secrets.CODECOV_TOKEN }}

      - name: Show testthat output
        if: always()
        run: |
          ## --------------------------------------------------------------------
          find '${{ runner.temp }}/package' -name 'testthat.Rout*' -exec cat '{}' \; || true
        shell: bash

      - name: Stop Papercheck API
        if: always()
        run: |
          if [ -f inst/plumber/api.pid ]; then
            kill $(cat inst/plumber/api.pid) || true
          fi
        shell: bash

      - name: Upload test results
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: coverage-test-failures
          path: ${{ runner.temp }}/package
